name: YAMDA-env
channels:
  - pytorch
  - anaconda
  - bioconda
  - conda-forge
  - defaults
  - anaconda-fusion
dependencies:
  - anaconda=custom=py36hbbc8b67_0
  - biopython=1.71=py36h637b7d7_0
  - bzip2=1.0.6=h9a117a8_4
  - ca-certificates=2018.03.07=0
  - certifi=2018.4.16=py36_0
  - cffi=1.11.5=py36h9745a5d_0
  - cudatoolkit=9.0=h13b8566_0
  - cudnn=7.1.2=cuda9.0_0
  - curl=7.60.0=h84994c4_0
  - expat=2.2.5=he0dffb1_0
  - freetype=2.8=hab7d2ae_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2018.0.0=8
  - jpeg=9b=h024ee3a_2
  - libcurl=7.60.0=h1ad7b7a_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libpng=1.6.34=hb9fc6fc_0
  - libssh2=1.8.0=h9cfc8f7_4
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - libtiff=4.0.9=he85c1e1_1
  - libxml2=2.9.8=hf84eae3_0
  - libxslt=1.1.32=h1312cb7_0
  - mkl=2018.0.2=1
  - mkl_fft=1.0.1=py36h3010b51_0
  - mkl_random=1.0.1=py36h629b387_0
  - nccl=1.3.5=cuda9.0_0
  - ncurses=6.1=hf484d3e_0
  - ninja=1.8.2=py36h6bb024c_1
  - numpy=1.13.3=py36hdbf6ddf_4
  - olefile=0.45.1=py36_0
  - openssl=1.0.2o=h20670df_0
  - pandas=0.23.0=py36h637b7d7_0
  - pillow=5.1.0=py36h3deb7b8_0
  - pip=10.0.1=py36_0
  - pycparser=2.18=py36hf9f622e_1
  - python=3.6.5=hc3d631a_2
  - python-dateutil=2.7.3=py36_0
  - pytorch=0.4.0=py36hdf912b8_0
  - pytz=2018.4=py36_0
  - readline=7.0=ha6073c6_4
  - scipy=0.19.1=py36h9976243_3
  - setuptools=39.1.0=py36_0
  - six=1.11.0=py36h372c433_1
  - sqlite=3.23.1=he433501_0
  - tk=8.6.7=hc745277_3
  - torchvision=0.2.1=py36_0
  - tqdm=4.23.3=py36_0
  - wheel=0.31.1=py36_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=ha838bed_2
  - bcftools=1.7=0
  - bedtools=2.27.1=1
  - ghostscript=9.18=1
  - htslib=1.7=0
  - meme=4.12.0=py36pl5.22.0_1
  - perl-cgi=4.22=3
  - perl-digest-hmac=1.03=pl5.22.0_1
  - perl-encode-locale=1.05=pl5.22.0_4
  - perl-file-listing=6.04=0
  - perl-html-parser=3.72=pl5.22.0_1
  - perl-html-tagset=3.20=pl5.22.0_1
  - perl-html-template=2.95=0
  - perl-html-tree=5.03=0
  - perl-http-cookies=6.01=0
  - perl-http-daemon=6.01=0
  - perl-http-date=6.02=pl5.22.0_1
  - perl-http-message=6.11=0
  - perl-http-negotiate=6.01=0
  - perl-io-html=1.001=pl5.22.0_1
  - perl-io-socket-ssl=2.024=0
  - perl-libwww-perl=6.15=0
  - perl-lwp-mediatypes=6.02=pl5.22.0_1
  - perl-mime-base64=3.15=pl5.22.0_0
  - perl-net-http=6.09=0
  - perl-net-ssleay=1.84=pl5.22.0_0
  - perl-ntlm=1.09=1
  - perl-scalar-list-utils=1.45=2
  - perl-test-more=1.001002=pl5.22.0_0
  - perl-threaded=5.22.0=pl5.22.0_12
  - perl-uri=1.71=pl5.22.0_1
  - perl-www-robotrules=6.02=0
  - perl-xml-namespacesupport=1.11=0
  - perl-xml-parser=2.44=4
  - perl-xml-sax=0.99=0
  - perl-xml-sax-base=1.08=0
  - perl-xml-sax-expat=0.51=0
  - perl-xml-simple=2.22=0
  - perl-xsloader=0.22=pl5.22.0_0
  - perl-yaml=1.24=0
  - pybedtools=0.7.10=py36_2
  - pyfaidx=0.5.3=py36_0
  - pysam=0.14.1=py36_htslib1.7_0
  - samtools=1.7=1
  - perl=5.22.0.1=0
  - pip:
    - torch==0.4.0
prefix: /home/darkhipo/anaconda3/envs/YAMDA-env

